import { k } from "../kaboomContext";

// ==============================
// Sounds (generated by `npm run sounds`)
// ==============================

const SOUNDS = ["flap", "score", "hit", "milestone", "highscore"] as const;
export type SoundName = typeof SOUNDS[number];

SOUNDS.forEach(name => k.loadSound(name, `/sounds/${name}.wav`))

// Browsers start the audio context suspended until a user gesture, and Kaboom
// doesn't resume it itself
const resumeAudio = () => {
    if (k.audioCtx.state === "suspended") k.audioCtx.resume()
}
window.addEventListener("keydown", resumeAudio)
window.addEventListener("pointerdown", resumeAudio)

// ==============================
// Mute (persisted)
// ==============================

const MUTED_KEY = "flappy.muted";

function loadMuted() {
    try {
        return localStorage.getItem(MUTED_KEY) === "true";
    } catch {
        return false;
    }
}

let muted = loadMuted();
k.volume(muted ? 0 : 1)

export function isMuted() {
    return muted
}

export function toggleMute() {
    muted = !muted
    k.volume(muted ? 0 : 1)
    try {
        localStorage.setItem(MUTED_KEY, muted.toString());
    } catch {
        // Storage unavailable: the setting just won't persist
    }
}

/** Registers the M key for the current scene (scene changes clear handlers). */
export function bindMuteKey(onChange?: () => void) {
    k.onKeyPress("m", () => {
        toggleMute()
        onChange?.()
    })
}

// ==============================
// Playback
// ==============================

export function playSound(name: SoundName) {
    if (!muted) k.play(name)
}
